apiVersion: v1
name: dex
version: 2.15.2
appVersion: 2.24.0
description: OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable Connectors
keywords:
- dex
- oidc
icon: https://github.com/dexidp/dex/raw/master/Documentation/logos/dex-glyph-color.png
home: https://github.com/dexidp/dex/
sources:
- https://github.com/dexidp/dex/
deprecated: true
