# Copyright 2019 Istio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in conformance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

collections:
  - name: "k8s/collection1"
    kind: "Kind1"
    group: "testdata.istio.io"

  - name: "collection1out"
    kind: "Kind1"
    group: "testdata.istio.io"

  - name: "k8s/collection2"
    kind: "Kind2"
    group: "testdata.istio.io"

  - name: "collection2out"
    kind: "Kind2"
    group: "testdata.istio.io"

resources:
  - kind: "Kind1"
    plural: "Kind1s"
    group: "testdata.istio.io"
    version: "v1alpha1"
    proto: "google.protobuf.Struct"
    protoPackage: "github.com/gogo/protobuf/types"

  - kind: "Kind2"
    plural: "Kind2s"
    group: "testdata.istio.io"
    version: "v1alpha1"
    optional: true
    clusterScoped: true
    proto: "google.protobuf.Struct"
    protoPackage: "github.com/gogo/protobuf/types"

transforms:
  - type: direct
    mapping:
      "k8s/collection1": "collection1out"
      "k8s/collection2": "collection2out"
