name: 'charts'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  charts:
    name: 'charts'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: 'charts:asdf:install'
      uses: asdf-vm/actions/install@v1.1.0

    - name: 'charts:python:install'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: 'charts:testing'
      uses: helm/chart-testing-action@v2.0.1

    - name: 'charts:particule'
      run: |
        helm lint charts/*
        helm package -d dist charts/*

    - name: 'charts:aws-ebs-csi-driver'
      run: |
        helm lint aws-ebs-csi-driver/charts/*
        helm package -d dist aws-ebs-csi-driver/charts/*

    - name: 'charts:istio'
      run: |
        helm lint istio/manifests/charts/istio-{operator,cni}
        helm package -d dist istio/manifests/charts/istio-{operator,cni}

    - name: 'charts:index'
      run: helm repo index --url https://particuleio.github.io/charts/ .
      working-directory: dist

    - name: 'charts:gh-pages'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
      if: github.ref == 'refs/heads/main'

    - name: 'charts:success'
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: SUCCESS
        color: good

    - name: 'charts:failure'
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: notifications
        status: failure
        color: danger
